services:
  mydb:
    image: mysql:latest
    container_name: user-8-mysql
    volumes:
      - u8-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: wordpressUser
      MYSQL_PASSWORD: P@ssw0rd
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -u root --password=P@ssw0rd || exit 1'
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  my-wordpress:
    depends_on:
      - mydb
    image: wordpress:latest
    container_name: user-8-wordpress
    environment:
      WORDPRESS_DB_HOST: mydb
      WORDPRESS_DB_USER: wordpressUser
      WORDPRESS_DB_PASSWORD: P@ssw0rd
      WORDPRESS_DB_NAME: mydatabase
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:80 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3

my-nginx:
    depends_on:
      - my-wordpress
    image: nginx:alpine
    container_name: user-8-nginx
    volumes:
      - /home/user-8/d2/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8008:80'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:80 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  u8-db-data: